### ISSUE TITLE
support for Holtek HT66F40 (Lerway) based models

### ISSUE THREAD

**Issue by dt** [matsstaff/stc1000p#100]
I just picked up a Lerway STC-1000 on Amazon and discovered, when I cracked it open to solder on a header for programming it, that the board wasn't quite the same as my old one, in particular it doesn't have the same programming header.

![img_2500](https://user-images.githubusercontent.com/15615/29302244-6df37276-8150-11e7-804b-a6c12cde3c59.JPG)

There are a couple empty headers on the main board though, labeled GND, VDD, RST, NTC 1 and NTC 2. A volt meter suggests pin out between the main board and front panel board is pretty similar to the old one: the same pins are tied to GND and VDD, the one that connects to the "RST" header seems to correspond to what I expected to be nMCLR. Whereas my old one had the 2nd and 3rd pins of connection between the board going to the ISCPCLK and ISCPDAT, the other two headers on this board, labeled NTC 1 and 2, correspond to the first and second pins, with no blank header I could find that corresponded to the third, which was ICSPCLK on my old one. Maybe this one does ISCP over the two NTC pins instead?

It looks like the chip itself is a Holtek HT66F40. 
![img_2498](https://user-images.githubusercontent.com/15615/29302254-888df340-8150-11e7-9669-706f4121eed2.JPG)

I tried poking it with the programming sketch as if the pin-out where exactly the same (using the corresponding pins on the junction between the boards), but couldn't read a device ID. I'm guessing this chip isn't supported, but I'm curious if anyone else has run into this chip or has any pointers on adding support for it.

**Comment by matsstaff** [comment]
This is a completely different architecture and is not and probably will not be supported by this project. You can search the massive thread on homebrewtalk and see that is has been discussed before. 
It would be cool though, if it could be 'hacked', but my gut feeling is that it is not really feasible.

The problems are (in order of importance):
* The documentation is lacking and in engrish. No specs of the prococol/timings used for flashing.
* No free tools. C compiler, flash programmer et.c. need to be bought from Holtek.

It would not be an impossible task. But hard. And probably cost a bit of cash. And without a free compiler, not really worthwhile.

**Comment by dt** [comment]
Thanks for the details!
