### ISSUE TITLE
The link to the STC-1000 on AliExpress is dead

### ISSUE THREAD

**Issue by leogout** [matsstaff/stc1000p#102]
Hi, the link to the AliExpress page on the README is no longer available. I whent to the manufacturer's page and found [this one](https://fr.aliexpress.com/item/STC-1000-A-400P-version-Digital-Temperature-Controller-Digital-LED-Temperature-Controller-220V-Thermostat-Sensor/32863068632.html?spm=a2g0w.10010108.1000016.1.e8ec57d2Zv0Flb&isOrigTitle=true), which is slightly more expensive because they bundled a thermal sensor with it. 
I think it's a legit A400_P version (and not a copy) but I would like your approval before modifying the README. What do you guys think ?

**Comment by matsstaff** [comment]
Yeah, they update their listings from time to time, so if the direct link is not working searching their store is the way to go.
I updated the link though :)
