### ISSUE TITLE
Aid

### ISSUE THREAD

**Issue by Kingaling04** [matsstaff/stc1000p#48]
Good afternoon, I am emailing you with the request of some aid for flashing my STC-1000. Is there another way that I could contact you and work on this together. I am attempting to combine the STC-1000 with a CoolZone brew jacket to automate the temperature controlling section of brewing.

**Comment by matsstaff** [comment]
If you have questions that others might benefit from, please ask in the HBT thread http://www.homebrewtalk.com/f258/stc-1000-a-464348/
For personal contact you can send me a PM on HBT (my username on HBT is alphaomega).
Cheers!
