### ISSUE TITLE
ITC-1000 Compatibility

### ISSUE THREAD

**Issue by DoomsDayBrewery** [matsstaff/stc1000p#50]
I just received 2 of the ITC-1000 Ink Bird dual temp controllers they appear to be identical to the STC-1000. Will your firmware work on that controller?
Regards,
mike

**Comment by matsstaff** [comment]
I think this was covered in the HBT thread, as it seems the ITC-1000 controller is not based on the A_400P version of the hardware, it will not be possible.
Closing this issue.
