### ISSUE TITLE
User defined temperature display

### ISSUE THREAD

**Issue by Kalsta** [matsstaff/stc1000p#62]
New settings menu option "CF", to toggle temperature display: "C" = Celsius; "F" = Fahrenheit.

This will prevent the need to support two firmware versions.

**Comment by matsstaff** [comment]
I'm closing this issue as a "won't fix". There is no 'good' way to do this. Even if there was, there is simply no way that both lookup tables et.c. would fit in program space (at least not without crippling other functionality).
Code wise, there is no need to support two versions, it is all done with conditional compilation from a single source, so only the affected lines are replaced at compile time. It is no harder (in fact it is probably easier) to maintain.
