### ISSUE TITLE
STC1000 version using N96A8211 conversion to PIC 16F1828 is possible. 

### ISSUE THREAD

**Issue by anil001** [matsstaff/stc1000p#63]
Having purchased two stc1000 from ebay and found them to be the version that uses the N96A8211 chip, I decided to do the conversion to PIC 16F1828.

The pin outs are completely different.
The button BTN_PWR and BTN_S  and BTN_UP and BTN_DOWN Addresses need to be swapped respectively in the software.
The temperature probe on the  N96A8211 operates in the opposite way to the PIC version.  
So that has to be changed. It requires a 10K ohm resistor pull down resistor on the input of the pic, with the temp probe connected between the pic (pin 18) input and  vcc. (+5)
The conversion can be done on a bit of prototyping board, there is enough space in the case for it. 

I’m toying with the idea of getting a small PCBs made that will hold the PIC chip and that can be soldered in place of the N96A8211… I’ll publish the pcb layout and or make the adaptor available if there is any interest.

**Comment by matsstaff** [comment]
Hi!
That is cool, please to keep us updated if you make any progress on this. As I said though in the HBT thread, there is a a known good source for the correct controllers now.
Also, don't think this is an issue with STC-1000+, so I will close this ticket and kindly ask you to keep the discussion to the HBT thread. Though, if you get this working satisfactionally and want to include instructions/PCB layout to the STC-1000+ project, I'd be glad to include it.
Cheers!
