### ISSUE TITLE
Dual Probe_Minute program

### ISSUE THREAD

**Issue by capt9859** [matsstaff/stc1000p#69]
Mat

Just set my system up and used the dual probe minute pic. I was under the impression that the duration times were in hours, are they only in minutes in this program? If so it limits each step to ~16.65 hours, am I able to reprogram it to the non-minute dual probe?

Also can you help me out with how you set up your dual probes, I have a good temp reading off both probes, but am not fully understanding how to properly use it to get the most out of it.

Thanks

Stu

**Comment by matsstaff** [comment]
Hi!

Please don't open issues on github, unless there is an actual (or suspected bug) or feature request or similar. Ask questions in this thread instead: http://www.homebrewtalk.com/showthread.php?t=464348

In short, there are different versions of the firmware. If you want hours, use picprog_probe2.ino (and not picprog_probe2_minute.ino, which is minute based).

For setting up dual probe, you probably need to make measurements on your setup for a typical fermentation. I have not done this myself, so I guess you are better off asking questions in the thread mentioned above.

Cheers!
