### ISSUE TITLE
Get Device ID error message

### ISSUE THREAD

**Issue by CNevay** [matsstaff/stc1000p#70]
Hey Matt, 

I'm trying to upload my 2nd controller but with a new Uno clone that I've never used before. When trying to upload the most recent picprog.ino to the uno, I am continually getting the following error message:

![capture](https://cloud.githubusercontent.com/assets/16394814/11946640/8e3896de-a811-11e5-8aff-06e98142af52.PNG)

Have you ever come across this before? 

Thank you again for the software, although I didn't buy a Black Box i still made a donation to the Dana-Farber Cancer Institute in your name, as a gesture of thanks. 

Thanks, 

Cam

**Comment by CNevay** [comment]
I uninstalled IDE 1.6.7, installed 1.6.3 and was able to upload the .ino file no problem. Please consider this closed.

**Comment by matsstaff** [comment]
Cool! Glad you got it working!
And big thanks for the donation! Very nice of you!
Cheers!
//mats
