### ISSUE TITLE
use Spark core

### ISSUE THREAD

**Issue by bateau84** [matsstaff/stc1000p#71]
Hey! Do you think you could use spark core to control the pid? (https://www.kickstarter.com/projects/sparkdevices/spark-core-wi-fi-for-everything-arduino-compatible)

**Comment by matsstaff** [comment]
Hi!
First off, please keep general discussion and questions to this thread: http://www.homebrewtalk.com/showthread.php?t=464348
Don't open issues unless you found a bug or have a specific request for an improvement.

But to answer your question: There is no PID here, but you probably could use the spark core to communicate with and control the STC. As it is arduino compatible, it would probably be pretty straightforward to get it working. Start with the communication firmware (picprog_com.ino) for the STC and the corresponding sketch (com.ino) for the spark core. Once you get it working, you can add wifi stuff to you hearts content.
Keep in mind wifi tend to use a bit of power and the STC can't deliver very much of it on the 5v rail. So, you'd almost certainly need external 5v for the spark core.
Note that this is not something I'd be willing to spend time on, but I think it would be doable (and pretty straightforward) if it something you'd like to try.

Good luck!
//mats
